version: '3.9'

services:
  demeter_postgres:
    image: postgres:16.2
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=demeter
      - POSTGRES_USER=demeter
      - POSTGRES_DB=demeter