CREATE TABLE recette (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    ingredient VARCHAR(255),
    description VARCHAR(255),
    plant_id INTEGER,
    CONSTRAINT fk_plant FOREIGN KEY (plant_id) REFERENCES plant(id) ON DELETE CASCADE
);

INSERT INTO recette (name, ingredient, description, plant_id) VALUES
('Tarte au citron', 'Pâte, citron, sucre, œufs', 'Cuire la pâte, préparer une crème citron, garnir.', 1),
('Limonade maison', 'Citrons, eau, sucre', 'Presser les citrons, mélanger avec eau et sucre.', 1),
('Poulet au citron', 'Poulet, citron, ail, huile', 'Mariner et cuire le poulet avec citron et ail.', 1),
('Salade d’orange', 'Oranges, cannelle, miel', 'Couper les oranges en rondelles, ajouter cannelle et miel.', 2),
('Gâteau à l’orange', 'Farine, sucre, œufs, jus d’orange', 'Mélanger les ingrédients, cuire au four.', 2),
('Canard à l’orange', 'Canard, oranges, miel, épices', 'Cuire le canard avec une sauce à l’orange.', 2),
('Purée de carottes', 'Carottes, beurre, crème', 'Cuire les carottes, mixer avec beurre et crème.', 3),
('Carottes râpées', 'Carottes, citron, huile d’olive', 'Râper les carottes, assaisonner.', 3),
('Soupe carotte-cumin', 'Carottes, oignon, cumin, bouillon', 'Cuire et mixer tous les ingrédients.', 3),
('Tarte aux mirabelles', 'Pâte brisée, mirabelles, sucre, crème', 'Étaler la pâte, disposer les mirabelles, ajouter la crème, cuire au four.', 4),
('Confiture de mirabelles', 'Mirabelles, sucre, jus de citron', 'Cuire les mirabelles avec sucre et citron, mettre en pot.', 4),
('Clafoutis aux mirabelles', 'Mirabelles, œufs, lait, farine, sucre', 'Mélanger la pâte, ajouter les mirabelles, cuire au four.', 4),
('Salade raisin-fromage', 'Raisins, fromage, noix, mâche', 'Mélanger les ingrédients avec une vinaigrette.', 5),
('Chutney de raisin', 'Raisins, vinaigre, sucre, épices', 'Cuire tous les ingrédients jusqu’à épaississement.', 5),
('Vin maison', 'Raisins, sucre, levure', 'Fermenter les raisins avec le sucre et la levure, filtrer.', 5),
('Salade Caprese', 'Tomates, mozzarella, basilic, huile d’olive, sel, poivre', 'Couper les tomates et la mozzarella en rondelles. Alterner les tranches avec du basilic. Assaisonner.', 6),
('Sauce tomate maison', 'Tomates, ail, oignon, huile d’olive, herbes', 'Faire revenir l’ail et l’oignon, ajouter les tomates concassées et les herbes. Laisser mijoter 30 min.', 6),
('Tomates farcies', 'Tomates, viande hachée, riz, ail, oignon, herbes', 'Évider les tomates, mélanger la chair avec la viande, le riz et l’assaisonnement. Remplir les tomates et cuire.', 6),
('Tarte aux fraises', 'Pâte sablée, fraises, crème pâtissière, sucre', 'Étaler la pâte, cuire à blanc, ajouter la crème pâtissière et les fraises coupées.', 7),
('Smoothie fraise-banane', 'Fraises, banane, yaourt, miel', 'Mixer tous les ingrédients jusqu’à consistance lisse.', 7),
('Confiture de fraises', 'Fraises, sucre, jus de citron', 'Cuire les fraises avec le sucre et le citron, mettre en pot.', 7),
('Sorbet framboise', 'Framboises, sucre, jus de citron', 'Mixer les framboises, ajouter le sucre et congeler en mélangeant régulièrement.', 8),
('Tiramisu framboise', 'Mascarpone, œufs, sucre, biscuits, framboises', 'Monter le mascarpone avec les œufs, alterner avec biscuits et framboises.', 8),
('Coulis de framboise', 'Framboises, sucre, eau', 'Mixer les framboises avec sucre et eau, filtrer.', 8),
('Purée de pommes de terre', 'Pommes de terre, beurre, lait', 'Écraser les pommes de terre cuites, ajouter beurre et lait.', 9),
('Gratin dauphinois', 'Pommes de terre, crème, ail, fromage', 'Disposer les pommes de terre en tranches avec crème et fromage, cuire au four.', 9),
('Frites maison', 'Pommes de terre, huile, sel', 'Couper en bâtonnets, frire à l’huile chaude.', 9),
('Radis au beurre', 'Radis, beurre, sel', 'Servir les radis avec du beurre et du sel.', 10),
('Salade de radis', 'Radis, concombre, vinaigrette', 'Couper en rondelles, mélanger avec vinaigrette.', 10),
('Tartines radis-fromage', 'Pain, radis, fromage frais', 'Tartiner du fromage sur du pain, ajouter des radis en rondelles.', 10),
('Choucroute maison', 'Chou, sel, vin blanc, saucisses', 'Fermenter le chou avec le sel, cuire avec vin et saucisses.', 11),
('Coleslaw', 'Chou, carottes, mayonnaise', 'Râper le chou et les carottes, mélanger avec mayonnaise.', 11),
('Chou farci', 'Chou, viande hachée, riz, sauce tomate', 'Farcir les feuilles de chou avec le mélange, cuire en sauce.', 11),
('Ratatouille', 'Aubergine, tomate, courgette, poivron', 'Couper et cuire tous les légumes ensemble.', 12),
('Caviar d’aubergine', 'Aubergines, huile d’olive, ail, citron', 'Cuire les aubergines, mixer avec ail et citron.', 12),
('Aubergines grillées', 'Aubergines, huile, herbes', 'Trancher et griller les aubergines avec huile et herbes.', 12),
('Velouté de butternut', 'Butternut, bouillon, crème', 'Cuire le butternut, mixer avec bouillon et crème.', 13),
('Gratin de butternut', 'Butternut, crème, fromage', 'Disposer en tranches avec crème et fromage, cuire au four.', 13),
('Butternut rôti au miel', 'Butternut, miel, thym', 'Couper en cubes, rôtir avec miel et thym.', 13),
('Navets glacés', 'Navets, beurre, sucre', 'Cuire les navets avec beurre et sucre pour caraméliser.', 14),
('Purée de navets', 'Navets, beurre, crème', 'Cuire et mixer avec beurre et crème.', 14),
('Soupe aux navets', 'Navets, bouillon, oignon', 'Cuire et mixer avec le bouillon.', 14),
('Salade César', 'Salade, poulet, croûtons, parmesan', 'Mélanger les ingrédients avec la sauce césar.', 15),
('Salade niçoise', 'Salade, thon, œufs, tomates, olives', 'Mélanger tous les ingrédients avec une vinaigrette.', 15),
('Wraps salade-poulet', 'Salade, poulet, tortilla, sauce', 'Garnir une tortilla avec la salade, le poulet et la sauce, rouler.', 15);
